export const ProfessionalTestData = {
  edgeCaseHighHourlyRate: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 999.99,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  edgeCaseLargeRadius: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 100,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  edgeCaseLongDescription: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'A'.repeat(1000),
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  edgeCaseManySkills: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: Array.from({ length: 50 }, (_, i) => `skill${i + 1}`),
  },

  edgeCaseZeroExperience: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'New professional',
    experienceYears: 0,
    hourlyRate: 20.0,
    interventionRadiusKm: 5,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestEmptyAddress: {
    address: '',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestEmptyCity: {
    address: '123 Test Street',
    city: '',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestEmptyPostalCode: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '',
    skills: ['skill1'],
  },

  invalidOnboardingRequestEmptySkills: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: [],
  },

  invalidOnboardingRequestMissingAddress: {
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestMissingCity: {
    address: '123 Test Street',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestNegativeExperience: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: -1,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestNegativeHourlyRate: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: -10.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  invalidOnboardingRequestNegativeRadius: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Test description',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: -5,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1'],
  },

  validOnboardingRequest: {
    address: '123 Test Street',
    city: 'Paris',
    description: 'Experienced professional with 5 years of experience',
    experienceYears: 5,
    hourlyRate: 50.0,
    interventionRadiusKm: 10,
    phone: '+33123456789',
    postalCode: '75001',
    skills: ['skill1', 'skill2', 'skill3'],
  },

  validOnboardingRequestMinimal: {
    address: '456 Minimal Street',
    city: 'Lyon',
    description: null,
    experienceYears: 0,
    hourlyRate: 25.0,
    interventionRadiusKm: 5,
    phone: null,
    postalCode: '69001',
    skills: ['skill1'],
  },
};
