-- ============================================================================
-- Model: news_letters
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."news_letters" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "email" text NOT NULL,
    "name" text,
    CONSTRAINT "news_letters_email_unique" UNIQUE ("email")
);

COMMENT ON TABLE "public"."news_letters" IS 'Newsletter subscriptions';
COMMENT ON COLUMN "public"."news_letters"."email" IS 'Subscriber email address';
COMMENT ON COLUMN "public"."news_letters"."name" IS 'Optional subscriber name';

CREATE INDEX IF NOT EXISTS "idx_news_letters_email" ON "public"."news_letters" ("email");

ALTER TABLE "public"."news_letters" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public to subscribe to newsletter" ON "public"."news_letters"
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- ============================================================================
-- Model: planning
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."planning" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "start_time" time without time zone NOT NULL,
    "end_time" time without time zone,
    "user" uuid DEFAULT auth.uid() NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    CONSTRAINT "planning_time_check" CHECK ("end_time" IS NULL OR "end_time" > "start_time")
);

COMMENT ON TABLE "public"."planning" IS 'User planning/schedule entries';
COMMENT ON COLUMN "public"."planning"."date" IS 'Date of the planning entry';
COMMENT ON COLUMN "public"."planning"."start_time" IS 'Start time of the planning entry';
COMMENT ON COLUMN "public"."planning"."end_time" IS 'End time of the planning entry (optional)';
COMMENT ON COLUMN "public"."planning"."user" IS 'Reference to the user who owns this planning entry';

CREATE INDEX IF NOT EXISTS "idx_planning_user" ON "public"."planning" ("user");
CREATE INDEX IF NOT EXISTS "idx_planning_date" ON "public"."planning" ("date");
CREATE INDEX IF NOT EXISTS "idx_planning_user_date" ON "public"."planning" ("user", "date");

CREATE TRIGGER update_planning_updated_at BEFORE UPDATE ON "public"."planning"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE "public"."planning" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own planning" ON "public"."planning"
    FOR SELECT
    TO authenticated
    USING (auth.uid() = "user");

CREATE POLICY "Users can insert their own planning" ON "public"."planning"
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = "user");

CREATE POLICY "Users can update their own planning" ON "public"."planning"
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = "user")
    WITH CHECK (auth.uid() = "user");

CREATE POLICY "Users can delete their own planning" ON "public"."planning"
    FOR DELETE
    TO authenticated
    USING (auth.uid() = "user");

-- ============================================================================
-- Model: profiles
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "user" uuid DEFAULT auth.uid() NOT NULL UNIQUE REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "first_name" text NOT NULL,
    "last_name" text,
    "email" text NOT NULL,
    "status" text DEFAULT 'created'::text NOT NULL,
    "role" "public"."role" NOT NULL,
    "phone" text,
    "jobs" text[],
    "postal_code" text,
    "city" text,
    "intervention_zone" text,
    "professional_email" text,
    "description" text,
    "experience" numeric,
    "hourly_rate" numeric,
    "avatar" text,
    CONSTRAINT "status_check" CHECK (("status" = ANY (ARRAY['created'::text, 'banned'::text, 'validated'::text]))),
    CONSTRAINT "experience_check" CHECK ("experience" IS NULL OR "experience" >= 0),
    CONSTRAINT "hourly_rate_check" CHECK ("hourly_rate" IS NULL OR "hourly_rate" >= 0)
);

COMMENT ON TABLE "public"."profiles" IS 'User profiles with extended information';
COMMENT ON COLUMN "public"."profiles"."status" IS 'Profile status: created, validated, or banned';
COMMENT ON COLUMN "public"."profiles"."role" IS 'User role: professional, structure, or admin';
COMMENT ON COLUMN "public"."profiles"."experience" IS 'Years of experience (must be >= 0)';
COMMENT ON COLUMN "public"."profiles"."hourly_rate" IS 'Hourly rate in currency (must be >= 0)';
COMMENT ON COLUMN "public"."profiles"."jobs" IS 'Array of job titles or specializations';

CREATE INDEX IF NOT EXISTS "idx_profiles_user" ON "public"."profiles" ("user");
CREATE INDEX IF NOT EXISTS "idx_profiles_email" ON "public"."profiles" ("email");
CREATE INDEX IF NOT EXISTS "idx_profiles_status" ON "public"."profiles" ("status");
CREATE INDEX IF NOT EXISTS "idx_profiles_role" ON "public"."profiles" ("role");

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON "public"."profiles"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public to create profiles" ON "public"."profiles"
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Users can view their own profile" ON "public"."profiles"
    FOR SELECT
    TO authenticated
    USING (auth.uid() = "user");

CREATE POLICY "Users can view public profiles" ON "public"."profiles"
    FOR SELECT
    TO authenticated, anon
    USING ("status" = 'validated');

CREATE POLICY "Users can update their own profile" ON "public"."profiles"
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = "user")
    WITH CHECK (auth.uid() = "user");

-- ============================================================================
-- Model: report
-- ============================================================================

CREATE TABLE IF NOT EXISTS "public"."report" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "title" text NOT NULL,
    "contents" text NOT NULL,
    "user" uuid DEFAULT auth.uid() NOT NULL REFERENCES "auth"."users"("id") ON DELETE CASCADE
);

COMMENT ON TABLE "public"."report" IS 'User reports or feedback';
COMMENT ON COLUMN "public"."report"."title" IS 'Report title';
COMMENT ON COLUMN "public"."report"."contents" IS 'Report content/description';
COMMENT ON COLUMN "public"."report"."user" IS 'Reference to the user who created this report';

CREATE INDEX IF NOT EXISTS "idx_report_user" ON "public"."report" ("user");
CREATE INDEX IF NOT EXISTS "idx_report_created_at" ON "public"."report" ("created_at");

CREATE TRIGGER update_report_updated_at BEFORE UPDATE ON "public"."report"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE "public"."report" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can create their own reports" ON "public"."report"
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = "user");

CREATE POLICY "Users can view their own reports" ON "public"."report"
    FOR SELECT
    TO authenticated
    USING (auth.uid() = "user");

CREATE POLICY "Users can update their own reports" ON "public"."report"
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = "user")
    WITH CHECK (auth.uid() = "user");

CREATE POLICY "Users can delete their own reports" ON "public"."report"
    FOR DELETE
    TO authenticated
    USING (auth.uid() = "user");

